#!/usr/bin/env bash
# Render the Homebrew formula for a release.
#
# Usage:
#   render.sh <tag> [repo] [outdir]
#     tag       release tag, for example 0.4.19
#     repo      owner/name (default: babeloff/mq-bridge-ros2)
#     outdir    output directory (default: ./out)
set -euo pipefail

TAG="${1:?usage: render.sh <tag> [repo] [outdir]}"
REPO="${2:-babeloff/mq-bridge-ros2}"
OUTDIR="${3:-out}"
VERSION="${TAG#v}"
BASE="https://github.com/${REPO}/releases/download/${TAG}"
NAME="mq-bridge-ros2"

sha() {
  local sum
  sum="$(curl -fsSL "${BASE}/${NAME}-${VERSION}-$1.tar.gz.sha256" | cut -d' ' -f1)"
  [[ "${sum}" =~ ^[0-9a-f]{64}$ ]] || {
    echo "bad checksum for $1: '${sum}'" >&2
    exit 1
  }
  echo "${sum}"
}

echo "resolving checksums for ${REPO} ${TAG} ..." >&2
MAC_ARM="$(sha aarch64-apple-darwin)"
MAC_X64="$(sha x86_64-apple-darwin)"
LINUX_X64="$(sha x86_64-unknown-linux-gnu)"
LINUX_ARM64="$(sha aarch64-unknown-linux-gnu)"

mkdir -p "${OUTDIR}/Formula"

cat > "${OUTDIR}/Formula/${NAME}.rb" <<RUBY
# typed: false
# frozen_string_literal: true
# Generated by packaging/homebrew/render.sh in ${REPO} — do not edit by hand.
class MqBridgeRos2 < Formula
  desc "ROS 2 endpoint plugin for mq-bridge"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE}/${NAME}-${VERSION}-aarch64-apple-darwin.tar.gz"
      sha256 "${MAC_ARM}"
    end
    on_intel do
      url "${BASE}/${NAME}-${VERSION}-x86_64-apple-darwin.tar.gz"
      sha256 "${MAC_X64}"
    end
  end

  on_linux do
    on_intel do
      url "${BASE}/${NAME}-${VERSION}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${LINUX_X64}"
    end
    on_arm do
      url "${BASE}/${NAME}-${VERSION}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${LINUX_ARM64}"
    end
  end

  def install
    (lib/"mq-bridge").install Dir["libmq_bridge_ros2.*"]
    doc.install "LICENSE"
  end

  test do
    ext = OS.mac? ? "dylib" : "so"
    assert_predicate lib/"mq-bridge/libmq_bridge_ros2.#{ext}", :exist?
  end
end
RUBY

echo "wrote ${OUTDIR}/Formula/${NAME}.rb" >&2
